### ISSUE TITLE
Git LFS

### ISSUE THREAD

**Issue by hugoboos** [lvbag/BAG-2.0-Extract#1]
Een clone van deze repository kost al `2.4G` aan opslag. Groeit de history elke maand dan met `2.4G`?

```
Cloning into 'BAG-2.0-Extract'...
remote: Enumerating objects: 87, done.
remote: Counting objects: 100% (87/87), done.
remote: Compressing objects: 100% (87/87), done.
remote: Total 652 (delta 14), reused 0 (delta 0), pack-reused 565
Receiving objects: 100% (652/652), 2.37 GiB | 12.00 MiB/s, done.
Resolving deltas: 100% (76/76), done.
Updating files: 100% (343/343), done.
```

Git is niet echt geschikt voor blob's. Wellicht is het beter om [Git LFS](https://git-lfs.github.com/) te gebruiken, object storage (S3) te gebruiken het gewoon op een file server neer te zetten?

**Comment by lvbag** [comment]
Hallo Hugo,
Bedankt voor de tip. We kenden Git LFS niet en gaan onderzoeken hoe dat werkt. 
Dit platform wordt nu tijdelijk gebruikt tot het reguliere leverproces is ingeregeld. Het is niet de bedoeling in die periode alle data hier te laten staan.  Wanneer er meer maanden zijn, wordt de eerste verwijderd. Die is dan toch verouderd.
