### ISSUE TITLE
Gemeente-extract voor grote gemeenten: waar is de dropbox-link?

### ISSUE THREAD

**Issue by jbgdb** [lvbag/BAG-2.0-Extract#2]
@lvbag 
#Goedemiddag, waar is de dropbox-link voor het gemeente-extract voor grote gemeenten?

**Comment by lvbag** [comment]
allereerst goed om te horen dat je de extracten gebruikt!
We hebben even een dropbox probleempje. We zijn hard aan het proberen deze te vullen en dan wordt de link gevuld.

**Comment by jbgdb** [comment]
> 
> 
> allereerst goed om te horen dat je de extracten gebruikt!
> We hebben even een dropbox probleempje. We zijn hard aan het proberen deze te vullen en dan wordt de link gevuld.

Prima! Wachten we daarop :)

**Comment by lvbag** [comment]
Het is gelukt en de link is opgenomen.
