### ISSUE TITLE
Ongeldige GML volgens PostGIS 2.5/3.0

### ISSUE THREAD

**Issue by bartnv** [lvbag/BAG-2.0-Extract#3]
Geen idee of dit de juiste plek is om dit probleem te melden, maar ik probeer het gewoon. Ik heb de GML-data uit BAG 2.0 Extract geprobeerd in PostGIS in te lezen met de ST_GeomFromGML() functie, maar dan krijg ik "ERROR: invalid GML representation" terug. Na wat spitten blijkt dat PostGIS het attribuut srsDimension="3" verwacht in de gml:posList tag. De oude BAG Extract had die wel en kon altijd al goed worden ingelezen. Ik heb niet de spec erop nageslagen om te beoordelen of dit een bug in PostGIS of in BAG 2.0 is, maar wellicht is het het makkelijkste om het aan deze kant op te lossen.

**Comment by lvbag** [comment]
Hallo Bart, 
in het extract wordt het attribuut srsDimension gebruikt en ingevuld. 
Uit je vraag kan ik niet halen of je hebt geprobeerd om een voorbeeld-extract in te lezen of een extract dat in productie is gemaakt. Het zou hetzelfde moeten zijn, maar mogelijk zit er toch ergens een foutje.

**Comment by bartnv** [comment]
Ik heb getest met de productie-extracten die hier op Github gepubliceerd zijn. De kwestie draait om aan welke tag het srsDimension attribuut hangt. In de BAG 2.0 extracten hangt dit attribuut aan de gml:Polygon tag, terwijl PostGIS verwacht dat ie aan de gml:posList tag hangt. Zo is het ook in de oude BAG Extract.

**Comment by marijnz0r** [comment]
Ik ben ook bezig met het uitlezen van de BAG 2.0-extracten en ik kwam deze issue tegen.
Vervolgens ben ik bij de GML-standaard gaan kijken op [https://www.ogc.org/standards/gml](https://www.ogc.org/standards/gml)
Daar stond de specificatie voor GML 3.3: [https://portal.opengeospatial.org/files/?artifact_id=46568 (PDF)](https://portal.opengeospatial.org/files/?artifact_id=46568)
Op pagina 43 vond ik dit terug voor een element met het attribuut srsDimension met een posList als child element:

```
<gml:LineString srsName="..." srsDimension="3" gml:id="LS_BH18">
<gml:posList>407829 268621 23.93 407415 268600 8.43</gml:posList>         
</gml:LineString>
```

Blijkbaar hoort de srsDimension toch op de parent van de posList thuis.

**Comment by bartnv** [comment]
Bedankt. Die documentatie is precies zo onleesbaar als ik me had voorgesteld ;-) Maar ik heb nog wat discussie over deze kwestie gevonden in een ticket van GDAL: https://trac.osgeo.org/gdal/ticket/5606

Lijkt erop dat PostGIS dus afwijkt van de norm door srsDimension als attribute van de posList te vereisen. Als ik nog eens tijd over heb zal ik daar een bugreport indienen. Voor nu los ik het op door de conversie buiten PostGIS om te doen.

In elk geval geen bug van BAG2.0, dus ik zal dit issue sluiten.
