### ISSUE TITLE
Grote gemeenten

### ISSUE THREAD

**Issue by marijnz0r** [lvbag/BAG-2.0-Extract#4]
De link naar [grote gemeenten](https://www.dropbox.com/sh/vm5wz15yt9tj9hz/AABeZ_oxd_grFAp60eStBGBMa?dl=0) uit [https://github.com/lvbag/BAG-2.0-Extract/blob/master/BAG%202.0%20gemeente%20extracten%20productie/Peildatum%2001-05-2020/Grote%20gemeente%20extracten.md](https://github.com/lvbag/BAG-2.0-Extract/blob/master/BAG%202.0%20gemeente%20extracten%20productie/Peildatum%2001-05-2020/Grote%20gemeente%20extracten.md) werkt niet meer.

Zou ik hiervan op korte termijn weer gebruik van kunnen maken?

**Comment by lvbag** [comment]
Aangezien er maandelijks nieuwe bestanden bijkomen en een aantal bestanden redelijk groot zijn is ervoor gekozen om de bestanden 3 maanden via Github beschikbaar te stellen. Indien u een Extract wenst te ontvangen welke niet (meer) op Github staat, kunt u dit bij ons opvragen via bag@kadaster.nl.

Met vriendelijke groet,
Nathalie Vos
