### ISSUE TITLE
BAG 2.0 gemeente extracten (peildatum 01-09-2020) XSD v20180601 ipv v20200601?

### ISSUE THREAD

**Issue by kanariezwart** [lvbag/BAG-2.0-Extract#5]
Ik begrijp dat de xml's vanaf "peildatum 01-09-2020" conform v20200601 XSD schema zijn uitgegeven.
Maar ik zie dat gemeentebestanden nog in het oude schema staan (v20180601). 

Klopt dat? Zouden deze niet in het nieuwe schema moeten worden uitgegeven?

**Comment by kanariezwart** [comment]
> zijn

den

**Comment by lvbag** [comment]
Het klopt dat er de nieuwe gemeentebestanden nog niet op Github zijn gepubliceerd. Er zijn nog een tweetal kleine aanpassingen doorgevoerd in de XSD's. Vanaf 15 oktober zullen de nieuwe gemeente Extracten op Github worden geplaatst. Het leveren van de gemeente Extracten zullen vanaf dat moment maandelijks op de 15e aangemaakt worden en handmatig op Github geplaatst gaan worden. Het levermoment is in lijn met de leveringen in de abonnementsvorm van het BAG 2.0 Extract van een gemeente.

**Comment by lvbag** [comment]
De gemeente extracten op basis van de nieuwe XSD's zijn op Github gepubliceerd.

**Comment by lvbag** [comment]
De gemeente extracten op basis van de nieuwe XSD's zijn op Github gepubliceerd.
