### ISSUE TITLE
Link naar BAG-2.0-Extract/Heel Nederland Extract/ werkt niet

### ISSUE THREAD

**Issue by JurritBZ** [lvbag/BAG-2.0-Extract#6]
Link naar BAG-2.0-Extract/Heel Nederland Extract/ werkt niet:
https://service10.kadaster.nl/gds2/download/public/5f40c6ec-4ff9-444d-9bc5-107949992615

Foutmelding:
```
This service10.kadaster.nl page can’t be found 
No webpage was found for the web address:
https://service10.kadaster.nl/gds2/download/public/29839643-9469-4d96-875a-fa4bb2f11c96
HTTP ERROR 404
```

**Comment by JurritBZ** [comment]
Trouwens. Ik kan de extracten nu wel vinden via deze link: https://extracten.bag.kadaster.nl/lvbag/extracten/ via de pagina https://www.kadaster.nl/zakelijk/producten/adressen-en-gebouwen/bag-2.0-extract

**Comment by NathalieVos** [comment]
Bedankt voor de melding.

Het klopt inderdaad dat BAG 2.0 Extracten, waaronder het heel Nederland Extract, via de externe server https://extracten.bag.kadaster.nl/lvbag/extracten/ beschikbaar worden gesteld.
Het bestand met de informatie over het BAG 2.0 heel Nederland Extract heb ik zojuist aangepast.

Met vriendelijke groet,
Nathalie Vos
