### ISSUE TITLE
Fouten gevonden in Heel Nederland export 08112020 nummeraanduidingen 

### ISSUE THREAD

**Issue by berendengelbrecht** [lvbag/BAG-2.0-Extract#7]
Ik ben bezig met het genereren van een postcodetabel voor onze klanten uit de maandelijkse Heel Nederland export (voorheen gebruikten we daar de BAG Compact-leveringen voor). Nu vond ik een aantal postcode/huisnummer-combinaties waarin de export afwijkt van de BAG Viewer @https://bagviewer.kadaster.nl/. Ik denk dat dit fouten in de export zijn,, mogelijk fouten in de nieuwe brondatabase:

Bestand 9999NUM08112020-000198.xml	postcode: 3771XA	moet zijn: 3771XM	voor nummeraanduidingen 0203200001022351, 0203200001022354, 0203200001022357, 0203200001022360
Bestand 9999NUM08112020-000466.xml	postcode: 2011DW	moet zijn: 2019DW	voor nummeraanduiding 0392200000011292
Bestand 9999NUM08112020-000887.xml	postcode: 5251WT	moet zijn: 5251TW	voor nummeraanduiding: 0797200000829048
Bestand 9999NUM08112020-001103.xml	postcode: 7451WZ	moet zijn: 7451WS	voor nummeraanduiding: 1742200000295906

Met vriendelijke groet,

Berend Engelbrecht
Product Development
Decos Information Solutions

**Comment by lvbag** [comment]
Hallo Berend,

Ik heb de door jou aangegeven nummeraanduidingen eens nader onderzocht en ik ben tot de volgende conclusie gekomen: Het BAG 2.0 extract wat je hebt gedownload (Heel Nederland export 08112020) heeft een standtechnische datum van 8 november 2020. Mutaties na deze datum zijn dus niet meegenomen in dit extract. De nummeraanduidingen die jij noemt, zijn allen na 8 november nog gemuteerd waardoor deze mutaties  niet mee zijn genomen in het extract van november en (als het goed is) straks wel in het extract van december.

Met vriendelijke groet,

Elmer Knol
Medewerker Operationeel Informatiemanagement LV BAG
