### ISSUE TITLE
Nummeraanduiding mist versie 1 en 2 - Mutatie records geldigheid sluit niet aan

### ISSUE THREAD

**Issue by JurritBZ** [lvbag/BAG-2.0-Extract#8]
BAG Nummeraanduiding1940200003270149 gaat fout.

Op de BAG viewer bestaat alleen versie 3. Zouden versie 1 en 2 ook niet altijd moeten bestaan?

In het maand mutatie bestand "9999MUT08122020-08012021-000010" komt dit record voor. Dit zijn twee wijzingsrecords voor versie 1 en 2. En een toegevoegd record voor versie 3.

De geldigheid van versie 2 naar 3 sluit niet aan:

identificatie | voorkomenidentificatie | beginGeldigheid | eindGeldigheid | tijdstipRegistratie | eindRegistratie | tijdstipRegistratieLV | tijdstipEindRegistratieLV | tijdstipNietBagLV
------------ | ------------ | ------------ | ------------ | ------------ | ------------ | ------------ | ------------ | ------------
1940200003270149 | 1 | 2020-04-09 | 2021-05-01 | 2020-04-10T11:05:13.472 | 2020-12-15T13:55:20.878 | 2020-04-10T11:06:11.134 | 2020-12-15T14:38:49.297 | 
1940200003270149 | 2 | 2021-05-01 |  | 2020-12-15T13:55:20.878 |  | 2020-12-15T14:38:49.297 |  | 
1940200003270149 | 3 | 2020-04-09 |  | 2020-12-23T15:28:51.236 |  | 2020-12-23T15:29:38.541 |  | 

De records hebben geen tijdstipNietBagLV dat gevuld is wat een delete van versie 1 en 2 zou kunnen betekenen.

Mogelijk gaan er nog meer records fout. Dit kan je dan zelf controleren door te checken of er versies missen.

**Comment by NicoleKortoomsBAG** [comment]
Hallo Jurrit,
Ik kijk in de API en daar zie ik dat voorkomen 1 en 2 een tijdstip Inactief hebben. Daardoor zijn ze niet zichtbaar in de viewer.

**Comment by JurritBZ** [comment]
OK. Maar op welke manier krijg ik dan door in het mutatie bestand dat dit record op inactief is gezet?

**Comment by NathalieVos** [comment]
Hallo Jurrit,

In het mutatiebestand van het BAG 2.0 Extract is bij de _wordt_ voor voorkomen 1 en bij de _wordt_ voor voorkomen 2 een tijdstipInactief opgenomen. Beide voorkomen zijn op hetzelfde moment inactief geworden door deze toevoeging in de _wordt_; _<Historie:tijdstipInactiefLV>2020-12-23T15:29:38.541</Historie:tijdstipInactief>_
De bronhouder heeft het tweede voorkomen een Begindatum in de toekomst gegeven, namelijk 2021-05-01. Doordat de begindatum in de toekomst ligt krijgt deze, als dit wordt ingetrokken, een tijdstipInactief. Wat inhoudt dat voorkomen 2 met een begindatum van 1 mei 2021 nooit een onderdeel uit zal maken van de levenscyclus van het object.

**Comment by JurritBZ** [comment]
Bedankt Nathalie,

Dit lost het voor me op.

**Comment by JurritBZ** [comment]
Bedankt Nathalie,

Dit lost het voor me op.
